plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.141'
    id "me.modmuss50.mod-publish-plugin" version "0.7.4"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "${mod_version}+mc${minecraft_version}"
group = 'com.vadis365.mob_grinding_utils'
base {
    archivesName = "mob_grinding_utils"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)
sourceSets.main.resources { srcDir 'src/generated/resources' }

neoForge {
    version = project.neo_version
    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', "mob_grinding_utils"
            programArguments.addAll('--width', '1280', '--height', '720')
        }
        client2 {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', "mob_grinding_utils"
            programArguments.addAll('--width', '1280', '--height', '720')
            programArguments.addAll('--username', 'Dev2')
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', "mob_grinding_utils"
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', "mob_grinding_utils"
        }

        data {
            clientData()
            programArguments.addAll '--mod', "mob_grinding_utils", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach { run ->
            jvmArgument '-Xmx8G'
            if (run.project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
                run.jvmArgument("-XX:+AllowEnhancedClassRedefinition")
            }
        }
    }
    mods {
        "mob_grinding_utils" {
            sourceSet(sourceSets.main)
        }
    }
}


repositories {
    maven { url = 'https://maven.creeperhost.net/' }
    maven { url "https://www.cursemaven.com" }
}

dependencies {
    compileOnly "mezz.jei:jei-${jei_mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${jei_mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${jei_mc_version}-neoforge:${jei_version}"

    runtimeOnly "curse.maven:JADE-324717:7886513"
    //runtimeOnly "curse.maven:ATLAS-633577:5490697"

    //runtimeOnly "curse.maven:PP-657831:6304429"
    //runtimeOnly "curse.maven:top-245211:5084077"
    //runtimeOnly fg.deobf("curse.maven:playermobs-430513:3153298") //Not ported yet
    //runtimeOnly "curse.maven:mek-268560:6327955"
    //runtimeOnly "curse.maven:RS-243076:6391989"
    //runtimeOnly fg.deobf("curse.maven:IF-266515:3261176")
    //runtimeOnly fg.deobf("curse.maven:TITANIUM-287342:3223141")
    //runtimeOnly fg.deobf("curse.maven:XNET-260912:3140153")
    //runtimeOnly fg.deobf("curse.maven:RFTBASE-326041:3206945")
    //runtimeOnly fg.deobf("curse.maven:MCJTYLIB-233105:3236516")
    //runtimeOnly fg.deobf("curse.maven:COFHCORE-69162:3249453")
    //runtimeOnly fg.deobf("curse.maven:TE-69163:3247000")
    //runtimeOnly fg.deobf("curse.maven:TF-222880:3248150")
    //runtimeOnly fg.deobf("curse.maven:CLUMPS-256717:3481298")
    //runtimeOnly fg.deobf("curse.maven:CYCLIC-239286:3708026")
}

jar {
    manifest {
        attributes([
            "Specification-Title": "mob_grinding_utils",
            "Specification-Vendor": "vadis365",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}